name: tmx_parser
version: 0.2.0
description: A cross platform parser for files created by Tiled Map Editor
homepage: https://github.com/aeb-dev/tmx_parser
repository: https://github.com/aeb-dev/tmx_parser
issue_tracker: https://github.com/aeb-dev/tmx_parser/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  xml: ^6.1.0
  meta: ^1.7.0
  json_events: ^1.0.1
  collection: ^1.17.0

dev_dependencies:
  test: ^1.21.4
  aeb_lint: ^1.0.0
