name: tmx_parser
version: 0.3.0
description: A cross platform parser for files created by Tiled Map Editor
homepage: https://github.com/aeb-dev/tmx_parser
repository: https://github.com/aeb-dev/tmx_parser
issue_tracker: https://github.com/aeb-dev/tmx_parser/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  json_events: ^1.2.0
  meta: ^1.10.0
  xml: ^6.5.0

dev_dependencies:
  aeb_lint: ^1.1.0
  test: ^1.21.4
