name: tmx_parser
version: 0.1.2
description: A cross platform parser for files created by Tiled Map Editor
homepage: https://github.com/MrMuMu/tmx_parser
repository: https://github.com/MrMuMu/tmx_parser
issue_tracker: https://github.com/aeb-dev/tmx_parser/issues

dependencies:
  xml: ^5.3.1
  universal_io: ^2.0.4

environment:
  sdk: ">=2.15.0 <3.0.0"
